# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				goat = true
				item_frame = true
				horse = true
				vindicator = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				shulker_bullet = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				end_crystal = true
				cat = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				eye_of_ender = true
				wither_skull = true
				villager = true
				wolf = true
				fishing_bobber = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				wither = true
				panda = true
				guardian = true

			[light_sources.settings.entities.sit]
				entity_sit = true

